### PR TITLE
[WIP] Update latest OpenTracing

### PR DESCRIPTION
**Pull request by mdedetrich**
This is a PR that attempts to update to the latest version of OpenTracing 0.33.0, fixing #6 . Auto closing spans is something that is no longer supported in OpenTracing 0.33.0 so this functionality has been removed.

Note that for some reason, one test is still failing, i.e.

```
- testNoActiveSpan *** FAILED ***
  {traceId:1, spanId:2, parentId:0, operationName:"one"} did not equal null (TracedExecutionContextTest.scala:75)
```

For some reason the `testPropagation` test is leaving over the span and its not getting reset by `mockTracer.reset()`, do you have any idea what could be going on here?

### CODE REVIEW

**Comment by malafeev** [comment]
@mdedetrich how about to copy `AutoFinishScopeManager`, `AutoFinishScope` from `opentracing-util` 0.31.0 to this library? 
In that case we will continue to support `TracedAutoFinishExecutionContext`.

**Comment by malafeev** [comment]
cc @carlosalberto

**Comment by mdedetrich** [comment]
@malafeev I think the intention is that there shouldn't be anything like `AutoFinishScopeManager`. The whole point to the changes in 0.32.0 (which got deprecated in 0.33.0) is that its the scope's responsibility to close itself to prevent abuse from people misusing the `ScopeManager`/`Scope`.

**Comment by malafeev** [comment]
> to prevent abuse from people misusing...

it can be true for general api, but for specific case it can make sense to have own `AutoFinishScopeManager`. I don't see any other solution for this lib except dropping it as you did.

**Comment by mdedetrich** [comment]
> it can be true for general api, but for specific case it can make sense to have own AutoFinishScopeManager

Well technically speaking this library just provides something analogous to `ThreadLocalScopeManager` which is one that works with `Future`. One uses a `ThreadLocal` to store the scope, the other uses an `ExecutionContext`, otherwise they are pretty much the same.

>  I don't see any other solution for this lib except dropping it as you did.

Exactly, which is why I dropped it, it doesn't make sense. Note that with OpenTracing API 0.33.0, users of this API will also have to adjust themselves wrt how to close `Scope`'s. I think its more beneficial to be consistent, the whole point of the `ScopeManager` abstraction is to cleanly separate how the `SpanContext` is passed along, i.e. its meant to be completely separate to how you finish the scopes (which should remain the same regardless of what `ScopeManager` you happen to be using and this is the point of the latest changes in the API if I understand them correctly)

**Comment by malafeev** [comment]
updated to 0.33.0

**Pull request closed without merging**
